export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const IMPORT_REPO_BEGIN = 'IMPORT_REPO_BEGIN'
export const IMPORT_REPO_SUCCESS = 'IMPORT_REPO_SUCCESS'
export const IMPORT_REPO_ERROR = 'IMPORT_REPO_ERROR'

export const GET_REPOS_BEGIN = 'GET_REPOS_BEGIN'
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS'

export const GET_DETAIL_BEGIN = 'GET_DETAIL_BEGIN'
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS'

export const DELETE_REPO_BEGIN = 'DELETE_REPO_BEGIN'
export const DELETE_REPO_SUCCESS = 'DELETE_REPO_SUCCESS'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'

export const SET_SELECTEDLIST = 'SET_SELECTEDLIST'

export const GET_DETAILS_BEGIN = 'GET_DETAILS_BEGIN'
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS'
